let cart = [
    {name:'Lavazza',
    price:100,
    id:1,
    count:1,
    size:'X',
    img:'image/product1 1.png'},
    {name:'Capuchino',
    price:200,
    id:2,
    count:1,
    size:'XL',
    img:'image/product1 1.png'},
    {name:'MacCoffe',
    price:300,
    id:3,
    count:1,
    size:'XXL',
    img:'image/product1 1.png'},
    {name:'Esspreso',
    price:400,
    id:4,
    count:1,
    size:'L',
    img:'image/product1 1.png'},

]